CREATE TABLE "Zmst" (
  "Group_ID" uuid,
  "Z_code" varchar,
  "LocalCode" integer,
  "gun_cd" integer,
  "Tou_cd" integer,
  "Zin_cd" integer,
  "Z_name" varchar,
  "D_S" integer,
  "lss" float,
  "Enj" float,
  "Ene" float,
  "Wat" float,
  "Ami" float,
  "Pro" float,
  "Tri" float,
  "Cho" float,
  "Lip" float,
  "Fac" float,
  "Sat" float,
  "Mon" float,
  "Pol" float,
  "Pn3" float,
  "Pn6" float,
  "Ara" float,
  "Epa" float,
  "Dha" float,
  "Vlm" float,
  "Cvl" float,
  "Vld" float,
  "Tot" float,
  "Ply" float,
  "Car" float,
  "Ora" float,
  "Ash" float,
  "Nat" float,
  "Kal" float,
  "Cal" float,
  "Mag" float,
  "Pho" float,
  "Iro" float,
  "Zin" float,
  "Cop" float,
  "Man" float,
  "Iod" float,
  "Sel" float,
  "Chr" float,
  "Mol" float,
  "Ret" float,
  "Caa" float,
  "Cab" float,
  "Cry" float,
  "Bca" float,
  "Ere" float,
  "ViD" float,
  "ToA" float,
  "ToB" float,
  "ToG" float,
  "ToD" float,
  "ViK" float,
  "VB1" float,
  "VB2" float,
  "Nia" float,
  "Eni" float,
  "VB6" float,
  "B12" float,
  "Fol" float,
  "Pan" float,
  "Bio" float,
  "ViC" float,
  "Alc" float,
  "Esa" float,
  "Wca" float,
  "Txt" text,
  "deleted" integer,
  "locked_by" uuid,
  "locked_at" timestamp,
  "Update_at" timestamp,
  PRIMARY KEY ("Group_ID", "LocalCode")
);

CREATE TABLE "tan_m" (
  "Group_ID" uuid,
  "Z_Code" varchar,
  "LocalCode" integer,
  "tan_cd" integer,
  "tan_Name" varchar,
  "jun" float,
  "jyuuryou" float,
  PRIMARY KEY ("Group_ID", "LocalCode", "tan_cd")
);

CREATE TABLE "Ry_lib" (
  "Group_ID" uuid,
  "Ry_Code" uuid,
  "Name" varchar,
  "Type" integer,
  "Update_at" timestamp,
  "Parent" uuid,
  "Ninzu" integer DEFAULT 1,
  "Ry_note" text,
  "locked_by" uuid,
  "locked_at" timestamp,
  PRIMARY KEY ("Group_ID", "Ry_Code")
);

CREATE TABLE "Ry_lib_s" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "Group_ID" uuid,
  "Ry_Code" uuid,
  "LocalCode" integer,
  "sort_no" integer,
  "Z_code" varchar,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer,
  PRIMARY KEY ("id", "Group_ID", "Ry_Code")
);

CREATE TABLE "Ko_Lib" (
  "Group_ID" uuid,
  "Ko_Code" uuid,
  "Name" varchar,
  "Update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  "locked_by" uuid,
  "locked_at" timestamp,
  PRIMARY KEY ("Group_ID", "Ko_Code")
);

CREATE TABLE "Ko_Lib_Ry" (
  "Group_ID" uuid,
  "Ko_Code" uuid,
  "sort_no" integer,
  "Ry_Code" uuid,
  "M_code" integer,
  "Name" varchar,
  "Ninzu" integer DEFAULT 1,
  "update_at" timestamp,
  "Rymemo" text,
  PRIMARY KEY ("Group_ID", "Ko_Code", "Ry_Code")
);

CREATE TABLE "Ko_Lib_Ry_s" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "Group_ID" uuid,
  "Ko_Code" uuid,
  "Ry_Code" uuid,
  "M_code" uuid,
  "sort_no" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer,
  PRIMARY KEY ("id", "Group_ID", "Ko_Code", "Ry_Code")
);

CREATE TABLE "Diary" (
  "Group_ID" uuid,
  "D_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  "SelectDay" timestamp,
  PRIMARY KEY ("Group_ID", "D_Code")
);

CREATE TABLE "D_Ko" (
  "Group_ID" uuid,
  "D_Code" uuid,
  "Ko_Day" timestamp,
  "D_Ko_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  PRIMARY KEY ("Group_ID", "D_Code", "D_Ko_Code")
);

CREATE TABLE "D_Ry" (
  "Group_ID" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "M_code" integer,
  "sort_no" integer,
  "D_Ry_Code" uuid,
  "Name" varchar,
  "Ninzu" integer,
  "Rymemo" text,
  "update_at" timestamp,
  PRIMARY KEY ("Group_ID", "D_Code", "Ko_Code", "D_Ry_Code")
);

CREATE TABLE "D_Ry_s" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "Group_ID" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "M_code" integer,
  "D_Ry_Code" uuid,
  "sort_no" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer,
  PRIMARY KEY ("id", "Group_ID", "D_Code", "Ko_Code", "D_Ry_Code")
);

CREATE TABLE "ProvideMeal" (
  "Group_ID" uuid,
  "Pro_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  "D_Code" uuid,
  "Parcent" float,
  "locked_by" uuid,
  "locked_at" timestamp,
  PRIMARY KEY ("Group_ID", "Pro_Code")
);

CREATE TABLE "GroupIB" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "Group_ID" uuid,
  "Pro_Code" uuid,
  "Nutrition" varchar,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float,
  PRIMARY KEY ("id", "Group_ID", "Pro_Code")
);

CREATE TABLE "ParsonCount" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "Group_ID" uuid,
  "Pro_Code" uuid,
  "Ko_Day" timestamp,
  "M_code" integer,
  "type" integer,
  "Count" integer,
  PRIMARY KEY ("id", "Group_ID", "Pro_Code")
);

CREATE TABLE "Groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "Group_ID" uuid,
  "Pro_Code" uuid,
  "Jun" integer,
  "age" integer,
  "sex" integer,
  "mens" integer,
  "preg" integer,
  "ActivityLevel" integer,
  "ParsonCount" integer,
  PRIMARY KEY ("id", "Group_ID", "Pro_Code")
);

CREATE TABLE "Meal" (
  "Group_ID" uuid,
  "M_Code" integer,
  "Sort_No" integer,
  "Name" varchar
);

CREATE TABLE "OrderFile" (
  "Group_ID" uuid,
  "Ord_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "InstName" varchar,
  "Zip" varchar,
  "Add" varchar,
  "Tel" varchar,
  "Fax" varchar,
  "locked_by" uuid,
  "locked_at" timestamp,
  PRIMARY KEY ("Group_ID", "Ord_Code")
);

CREATE TABLE "OrderGroup" (
  "Group_ID" uuid,
  "Ord_Code" uuid,
  "D_Code" uuid,
  PRIMARY KEY ("Group_ID", "Ord_Code", "D_Code")
);

CREATE TABLE "Dealers" (
  "Group_ID" uuid,
  "Ord_Code" uuid,
  "Deal_Code" integer,
  "Deal_Name" varchar,
  "t_name" varchar,
  "yuubin" varchar,
  "add1" varchar,
  "add2" varchar,
  "tel" varchar,
  "fax" varchar,
  "stop" integer,
  PRIMARY KEY ("Group_ID", "Ord_Code", "Deal_Code")
);

CREATE TABLE "OrderData" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "Group_ID" uuid,
  "Ord_Code" uuid,
  "Pro_Code" uuid,
  "D_Code" uuid,
  "Ko_Day" uuid,
  "M_Code" integer,
  "Z_Code" varchar,
  "LocalCode" integer,
  "OrderName" varchar,
  "Deal_Code" integer,
  "UserOrder" float,
  "StaffOrder" float,
  "tan_cd" integer,
  "DeliveryDate" timestamp,
  PRIMARY KEY ("id", "Group_ID", "Ord_Code", "Pro_Code", "D_Code", "Ko_Day")
);

CREATE TABLE "OrderNameList" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "Group_ID" uuid,
  "Ord_Code" uuid,
  "ONm_Code" integer,
  "Z_Code" varchar,
  "LocalCode" integer,
  "OrderName" varchar,
  PRIMARY KEY ("id", "Group_ID", "Ord_Code", "ONm_Code")
);

CREATE TABLE "w_CalcData" (
  "D_Code" uuid,
  "D_Name" varchar,
  "K_Code" uuid,
  "K_Name" varchar,
  "K_Day" timestamp,
  "RSort_no" int,
  "M_Code" int,
  "MealName" varchar,
  "R_Code" uuid,
  "R_Name" varchar,
  "ZSort_no" int,
  "Z_Code" varchar,
  "LocalCode" int,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" int,
  "TanSyoumi" float,
  "TanJunbi" float
);

CREATE TABLE "w_GroupIB" (
  "Group_ID" uuid,
  "Pro_Code" uuid,
  "Jun" integer,
  "Nutrition" varchar,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float,
  "ParsonCount" integer
);

CREATE TABLE "w_CalcDataRymemo" (
  "Group_ID" uuid,
  "D_Code" uuid,
  "D_Name" varchar,
  "Ko_Code" uuid,
  "Ko_Name" varchar,
  "Ko_Day" timestamp,
  "RSort_no" int,
  "M_Code" integer,
  "MealName" varchar,
  "Ry_Code" uuid,
  "Ry_Name" varchar,
  "Rymemo" varchar
);

CREATE TABLE "w_CalcOrderJyunbi" (
  "Group_ID" uuid,
  "Ord_Code" uuid,
  "Ko_Day" timestamp,
  "Z_Code" varchar,
  "LocalCode" integer,
  "UserJyunbi" float,
  "StaffJyunbi" float
);

CREATE TABLE "w_chg_zai" (
  "Group_ID" uuid,
  "Z_Code" varchar,
  "LocalCode" integer,
  "lss" float,
  "Wca" float,
  "EditUserID" uuid,
  "Update_at" timestamp
);

CREATE TABLE "w_D_Ko" (
  "Group_ID" uuid,
  "D_Code" uuid,
  "Ko_Day" timestamp,
  "Ko_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  PRIMARY KEY ("Group_ID", "D_Code", "Ko_Code")
);

CREATE TABLE "w_D_Ry" (
  "Group_ID" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "sort_no" int,
  "Ry_Code" uuid,
  "M_Code" int,
  "Name" varchar,
  "Ninzu" int,
  "update_at" timestamp,
  "Rymemo" varchar,
  PRIMARY KEY ("Group_ID", "D_Code", "Ko_Code", "Ry_Code")
);

CREATE TABLE "w_D_Ry_s" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "Group_ID" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "M_Code" int,
  "Ry_Code" uuid,
  "sort_no" int,
  "Z_code" varchar,
  "LocalCode" int,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" int,
  PRIMARY KEY ("id", "Group_ID", "D_Code", "Ko_Code", "Ry_Code")
);

CREATE TABLE "w_Grid_Ry_s" (
  "Group_ID" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "M_Code" integer,
  "meal_sort" integer,
  "Ry_Code" uuid,
  "ry_sort" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "z_sort" integer,
  "Syoumi" float,
  "tan_cd" integer
);

CREATE TABLE "w_Ko_Lib" (
  "Group_ID" uuid,
  "Ko_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  PRIMARY KEY ("Group_ID", "Ko_Code")
);

CREATE TABLE "w_Ko_Lib_Ry" (
  "Group_ID" uuid,
  "Ko_Code" uuid,
  "sort_no" integer,
  "Ry_Code" uuid,
  "M_Code" integer,
  "Name" varchar,
  "Ninzu" integer,
  "update_at" timestamp,
  "Rymemo" text,
  PRIMARY KEY ("Group_ID", "Ko_Code", "Ry_Code")
);

CREATE TABLE "w_Ko_Lib_Ry_s" (
  "Group_ID" uuid,
  "Ko_Code" uuid,
  "M_Code" integer,
  "Ry_Code" uuid,
  "sort_no" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer
);

CREATE TABLE "w_Ry_Lib" (
  "Group_ID" uuid,
  "Ry_Code" uuid,
  "Name" varchar,
  "Ninzu" integer,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  "Rymemo" text,
  PRIMARY KEY ("Group_ID", "Ry_Code")
);

CREATE TABLE "w_Ry_Lib_s" (
  "Group_ID" uuid,
  "Ry_Code" uuid,
  "sort_no" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer
);

CREATE TABLE "w_OrderData" (
  "id" int,
  "Group_ID" uuid,
  "Ord_Code" uuid,
  "Pro_Code" uuid,
  "ko_Day" timestamp,
  "M_Code" integer,
  "Jun" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "OrderName" varchar,
  "UserJyunbi" float,
  "StaffJyunbi" float,
  "Deal_Code" uuid,
  "UserOrder" float,
  "StaffOrder" float,
  "tan_cd" integer,
  "DeliveryDate" timestamp,
  PRIMARY KEY ("id", "Group_ID", "Ord_Code", "Pro_Code", "ko_Day")
);

CREATE TABLE "w_OrderGroup" (
  "Group_ID" uuid,
  "Ord_Code" uuid,
  "D_Code" uuid,
  PRIMARY KEY ("Group_ID", "D_Code")
);

CREATE TABLE "w_ParsonCount" (
  "Group_ID" uuid,
  "Pro_Code" uuid,
  "Ko_Day" timestamp,
  "M_Code" integer,
  "type" integer,
  "Count" integer
);

CREATE TABLE "w_ParsonCountHT" (
  "Group_ID" uuid,
  "Ord_Code" uuid,
  "Pro_Code" uuid,
  "Ko_Day" timestamp,
  "M_Code" integer,
  "type" integer,
  "Count" integer
);

CREATE INDEX "idx_ry_s_parent" ON "Ry_lib_s" ("Group_ID", "Ry_Code");

CREATE INDEX "idx_ry_s_zmst" ON "Ry_lib_s" ("Group_ID", "LocalCode", "tan_cd");

CREATE INDEX "idx_Ko_lib_ry_parent" ON "Ko_Lib_Ry" ("Group_ID", "Ko_Code");

CREATE INDEX "idx_Ko_Lib_ry_s_parent" ON "Ko_Lib_Ry_s" ("Group_ID", "Ko_Code", "Ry_Code");

CREATE INDEX "idx_Ko_Lib_ry_s_zmst" ON "Ko_Lib_Ry_s" ("Group_ID", "LocalCode", "tan_cd");

CREATE INDEX "idx_D_Ko_parent" ON "D_Ko" ("Group_ID", "D_Code");

CREATE INDEX "idx_D_Ry_parent" ON "D_Ry" ("Group_ID", "D_Code", "Ko_Code");

CREATE INDEX "idx_D_Ry_s_parent" ON "D_Ry_s" ("Group_ID", "D_Code", "Ko_Code", "D_Ry_Code");

CREATE INDEX "idx_D_Ry_s_zmst" ON "D_Ry_s" ("Group_ID", "LocalCode", "tan_cd");

CREATE INDEX "idx_GroupIB_ProvideMeal" ON "GroupIB" ("Group_ID", "Pro_Code");

CREATE INDEX "idx_ParsonCount_ProvideMeal" ON "ParsonCount" ("Group_ID", "Pro_Code");

CREATE INDEX "idx_OrderData_OrderFile" ON "OrderData" ("Group_ID", "Ord_Code", "Pro_Code", "D_Code", "Ko_Day");

CREATE INDEX "idx_OrderNameList_OrderFile" ON "OrderNameList" ("Group_ID", "Ord_Code");

COMMENT ON COLUMN "Zmst"."LocalCode" IS 'システム固有ID';

COMMENT ON COLUMN "Zmst"."D_S" IS '動物性植物性';

COMMENT ON COLUMN "Zmst"."lss" IS '廃棄率';

COMMENT ON COLUMN "Zmst"."Enj" IS 'エネルギーKj';

COMMENT ON COLUMN "Zmst"."Ene" IS 'エネルギーkcal';

COMMENT ON COLUMN "Zmst"."Wat" IS '水分';

COMMENT ON COLUMN "Zmst"."Ami" IS 'アミノ酸組成によるたんぱく質';

COMMENT ON COLUMN "Zmst"."Pro" IS 'たんぱく質';

COMMENT ON COLUMN "Zmst"."Tri" IS 'トリアシルグリセロール当量';

COMMENT ON COLUMN "Zmst"."Cho" IS 'コレステロール';

COMMENT ON COLUMN "Zmst"."Lip" IS '脂質';

COMMENT ON COLUMN "Zmst"."Fac" IS '脂肪酸総量';

COMMENT ON COLUMN "Zmst"."Sat" IS '飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Mon" IS '一価不飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Pol" IS '多価不飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Pn3" IS 'N3系多価不飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Pn6" IS 'N6系多価不飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Ara" IS 'アラキドン酸';

COMMENT ON COLUMN "Zmst"."Epa" IS 'イコサペンタエン酸';

COMMENT ON COLUMN "Zmst"."Dha" IS 'ドコサヘキサエン酸';

COMMENT ON COLUMN "Zmst"."Vlm" IS '利用可能炭水化物単糖当量';

COMMENT ON COLUMN "Zmst"."Cvl" IS '重量計利用可能炭水化物';

COMMENT ON COLUMN "Zmst"."Vld" IS '差引法利用可能炭水化物';

COMMENT ON COLUMN "Zmst"."Tot" IS '食物繊維総量';

COMMENT ON COLUMN "Zmst"."Ply" IS '糖アルコール';

COMMENT ON COLUMN "Zmst"."Car" IS '炭水化物';

COMMENT ON COLUMN "Zmst"."Ora" IS '有機酸';

COMMENT ON COLUMN "Zmst"."Ash" IS '灰分';

COMMENT ON COLUMN "Zmst"."Nat" IS 'ナトリウム';

COMMENT ON COLUMN "Zmst"."Kal" IS 'カリウム';

COMMENT ON COLUMN "Zmst"."Cal" IS 'カルシウム';

COMMENT ON COLUMN "Zmst"."Mag" IS 'マグネシウム';

COMMENT ON COLUMN "Zmst"."Pho" IS 'リン';

COMMENT ON COLUMN "Zmst"."Iro" IS '鉄';

COMMENT ON COLUMN "Zmst"."Zin" IS '亜鉛';

COMMENT ON COLUMN "Zmst"."Cop" IS '銅';

COMMENT ON COLUMN "Zmst"."Man" IS 'マンガン';

COMMENT ON COLUMN "Zmst"."Iod" IS 'ヨウ素';

COMMENT ON COLUMN "Zmst"."Sel" IS 'セレン';

COMMENT ON COLUMN "Zmst"."Chr" IS 'クロム';

COMMENT ON COLUMN "Zmst"."Mol" IS 'モリブデン';

COMMENT ON COLUMN "Zmst"."Ret" IS 'レチノール';

COMMENT ON COLUMN "Zmst"."Caa" IS 'αカロテン';

COMMENT ON COLUMN "Zmst"."Cab" IS 'βカロテン';

COMMENT ON COLUMN "Zmst"."Cry" IS 'βクリプトキサンチン';

COMMENT ON COLUMN "Zmst"."Bca" IS 'βカロテン当量';

COMMENT ON COLUMN "Zmst"."Ere" IS 'レチノール活性当量';

COMMENT ON COLUMN "Zmst"."ViD" IS 'ビタミンD';

COMMENT ON COLUMN "Zmst"."ToA" IS 'αトコフェロール';

COMMENT ON COLUMN "Zmst"."ToB" IS 'βトコフェロール';

COMMENT ON COLUMN "Zmst"."ToG" IS 'γトコフェロール';

COMMENT ON COLUMN "Zmst"."ToD" IS 'δトコフェロール';

COMMENT ON COLUMN "Zmst"."ViK" IS 'ビタミンK';

COMMENT ON COLUMN "Zmst"."VB1" IS 'ビタミンB1';

COMMENT ON COLUMN "Zmst"."VB2" IS 'ビタミンB2';

COMMENT ON COLUMN "Zmst"."Nia" IS 'ナイアシン';

COMMENT ON COLUMN "Zmst"."Eni" IS 'ナイアシン当量';

COMMENT ON COLUMN "Zmst"."VB6" IS 'ビタミンB6';

COMMENT ON COLUMN "Zmst"."B12" IS 'ビタミンB12';

COMMENT ON COLUMN "Zmst"."Fol" IS '葉酸';

COMMENT ON COLUMN "Zmst"."Pan" IS 'パントテン酸';

COMMENT ON COLUMN "Zmst"."Bio" IS 'ビオチン';

COMMENT ON COLUMN "Zmst"."ViC" IS 'ビタミンC';

COMMENT ON COLUMN "Zmst"."Alc" IS 'アルコール';

COMMENT ON COLUMN "Zmst"."Esa" IS '食塩相当量';

COMMENT ON COLUMN "Zmst"."Wca" IS '重量変化率';

COMMENT ON COLUMN "Zmst"."Txt" IS '備考';

COMMENT ON COLUMN "Zmst"."locked_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "Zmst"."Update_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "Ry_lib"."Type" IS '0:献立 / 1:フォルダ';

COMMENT ON COLUMN "Ry_lib"."Parent" IS '親フォルダのRy_Code';

COMMENT ON COLUMN "Ry_lib"."locked_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "Ry_lib_s"."Syoumi" IS '正味重量';

COMMENT ON COLUMN "Ry_lib_s"."Junbi" IS '準備重量';

COMMENT ON COLUMN "Ko_Lib"."Type" IS '0:献立 / 1:フォルダ';

COMMENT ON COLUMN "Ko_Lib"."locked_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "Diary"."Parent" IS '格納フォルダ';

COMMENT ON COLUMN "Diary"."SelectDay" IS '閉じる前に最後に選択された日';

COMMENT ON COLUMN "D_Ko"."D_Code" IS 'DiaryテーブルのID';

COMMENT ON COLUMN "D_Ko"."Ko_Day" IS 'timestamptz(6)';

COMMENT ON COLUMN "D_Ry"."D_Code" IS 'カレンダーID';

COMMENT ON COLUMN "D_Ry"."Ko_Code" IS '献立Code';

COMMENT ON COLUMN "D_Ry"."D_Ry_Code" IS '料理マスターCode';

COMMENT ON COLUMN "D_Ry"."Name" IS '実行時の料理名';

COMMENT ON COLUMN "D_Ry"."Ninzu" IS 'その日の人数';

COMMENT ON TABLE "D_Ry_s" IS 'ここをSUMして、Zmstの栄養価を掛ける。220万回のドラマがここに。';

COMMENT ON COLUMN "D_Ry_s"."D_Code" IS 'カレンダーID';

COMMENT ON COLUMN "D_Ry_s"."Ko_Code" IS '献立Code';

COMMENT ON COLUMN "D_Ry_s"."D_Ry_Code" IS 'D_Ryとの紐付け';

COMMENT ON COLUMN "D_Ry_s"."Z_code" IS '材料コード';

COMMENT ON COLUMN "D_Ry_s"."LocalCode" IS '旧PecNo';

COMMENT ON COLUMN "D_Ry_s"."Syoumi" IS '実行時の正味重量';

COMMENT ON COLUMN "D_Ry_s"."Junbi" IS '実行時の準備重量';

COMMENT ON COLUMN "ProvideMeal"."D_Code" IS '対象となるDiary（グループ）';

COMMENT ON COLUMN "ProvideMeal"."Parcent" IS '一日当りの栄養給与提供（%）１食の提供（１日分の食事を提供しない施設向け）';

COMMENT ON COLUMN "ProvideMeal"."locked_at" IS 'timestamptz(6)';

COMMENT ON TABLE "GroupIB" IS '食種ごとの栄養基準マッピング';

COMMENT ON TABLE "ParsonCount" IS '日々の提供食数';

COMMENT ON COLUMN "ParsonCount"."type" IS '利用者：職員';

COMMENT ON TABLE "Groups" IS '対象集団の属性定義';

COMMENT ON TABLE "Meal" IS '食事区分';

COMMENT ON TABLE "OrderFile" IS '発注データ。および発注書のヘッダー情報';

COMMENT ON COLUMN "OrderFile"."locked_at" IS 'timestamptz(6)';

COMMENT ON TABLE "OrderGroup" IS 'OrderFileに対してどのDiaryが紐づいているか';

COMMENT ON TABLE "Dealers" IS '業者マスタ';

COMMENT ON COLUMN "Dealers"."t_name" IS '担当者名';

COMMENT ON COLUMN "Dealers"."stop" IS '取引停止フラグ';

COMMENT ON TABLE "OrderData" IS '発注明細。材料×人数×端数処理の結果';

COMMENT ON COLUMN "OrderData"."DeliveryDate" IS '納入日';

COMMENT ON TABLE "OrderNameList" IS '材料呼称変換,全発注書データ共通';

COMMENT ON COLUMN "w_CalcData"."Junbi" IS 'gで保存すること';

COMMENT ON COLUMN "w_CalcData"."tan_cd" IS '印刷時など、状況に応じて使うこと';

COMMENT ON COLUMN "w_CalcData"."TanSyoumi" IS '単位数量で保存';

COMMENT ON COLUMN "w_CalcData"."TanJunbi" IS '単位数量で保存';

COMMENT ON COLUMN "w_GroupIB"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "w_GroupIB"."RDA" IS '推奨量';

COMMENT ON COLUMN "w_GroupIB"."AI" IS '目安量';

COMMENT ON COLUMN "w_GroupIB"."UL" IS '耐容上限量';

COMMENT ON COLUMN "w_GroupIB"."DG" IS '目安量';

COMMENT ON COLUMN "w_GroupIB"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "w_CalcDataRymemo"."Rymemo" IS '長いテキスト';

COMMENT ON COLUMN "w_chg_zai"."Update_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "w_D_Ko"."D_Code" IS 'DiaryテーブルのID';

COMMENT ON COLUMN "w_D_Ko"."Ko_Day" IS '献立の日付';

COMMENT ON COLUMN "w_D_Ry"."Ry_Code" IS '料理識別コード';

COMMENT ON COLUMN "w_D_Ry"."M_Code" IS '食事';

COMMENT ON COLUMN "w_D_Ry"."Name" IS '料理名';

COMMENT ON COLUMN "w_D_Ry"."Rymemo" IS '長いテキスト';

COMMENT ON COLUMN "w_Ko_Lib"."Type" IS '0:献立カレンダー / 1:フォルダ';

COMMENT ON COLUMN "w_Ko_Lib"."Parent" IS '格納フォルダ (再帰リレーション用)';

COMMENT ON COLUMN "w_Ko_Lib_Ry"."Ry_Code" IS '料理識別コード';

COMMENT ON COLUMN "w_Ko_Lib_Ry"."M_Code" IS '食事';

COMMENT ON COLUMN "w_Ko_Lib_Ry"."Name" IS '料理名';

COMMENT ON COLUMN "w_Ry_Lib"."Parent" IS '格納フォルダ';

ALTER TABLE "tan_m" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ry_lib_s" ADD FOREIGN KEY ("Group_ID", "Ry_Code") REFERENCES "Ry_lib" ("Group_ID", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ry_lib_s" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ry_lib_s" ADD FOREIGN KEY ("Group_ID", "LocalCode", "tan_cd") REFERENCES "tan_m" ("Group_ID", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ko_Lib_Ry" ADD FOREIGN KEY ("Group_ID", "Ko_Code") REFERENCES "Ko_Lib" ("Group_ID", "Ko_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ko_Lib_Ry_s" ADD FOREIGN KEY ("Group_ID", "Ko_Code", "Ry_Code") REFERENCES "Ko_Lib_Ry" ("Group_ID", "Ko_Code", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ko_Lib_Ry_s" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ko_Lib_Ry_s" ADD FOREIGN KEY ("Group_ID", "LocalCode", "tan_cd") REFERENCES "tan_m" ("Group_ID", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ko" ADD FOREIGN KEY ("Group_ID", "D_Code") REFERENCES "Diary" ("Group_ID", "D_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ry" ADD FOREIGN KEY ("Group_ID", "D_Code", "Ko_Code") REFERENCES "D_Ko" ("Group_ID", "D_Code", "D_Ko_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ry_s" ADD FOREIGN KEY ("Group_ID", "D_Code", "Ko_Code", "D_Ry_Code") REFERENCES "D_Ry" ("Group_ID", "D_Code", "Ko_Code", "D_Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ry_s" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ry_s" ADD FOREIGN KEY ("Group_ID", "LocalCode", "tan_cd") REFERENCES "tan_m" ("Group_ID", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ProvideMeal" ADD FOREIGN KEY ("Group_ID", "D_Code") REFERENCES "Diary" ("Group_ID", "D_Code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GroupIB" ADD FOREIGN KEY ("Group_ID", "Pro_Code") REFERENCES "ProvideMeal" ("Group_ID", "Pro_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ParsonCount" ADD FOREIGN KEY ("Group_ID", "Pro_Code") REFERENCES "ProvideMeal" ("Group_ID", "Pro_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Groups" ADD FOREIGN KEY ("Group_ID", "Pro_Code") REFERENCES "ProvideMeal" ("Group_ID", "Pro_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderGroup" ADD FOREIGN KEY ("Group_ID", "D_Code") REFERENCES "Diary" ("Group_ID", "D_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Dealers" ADD FOREIGN KEY ("Group_ID", "Ord_Code") REFERENCES "OrderFile" ("Group_ID", "Ord_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("Group_ID", "Ord_Code") REFERENCES "OrderFile" ("Group_ID", "Ord_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("Group_ID", "Pro_Code") REFERENCES "ProvideMeal" ("Group_ID", "Pro_Code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("Group_ID", "Ord_Code", "Deal_Code") REFERENCES "Dealers" ("Group_ID", "Ord_Code", "Deal_Code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("Group_ID", "LocalCode", "tan_cd") REFERENCES "tan_m" ("Group_ID", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderNameList" ADD FOREIGN KEY ("Group_ID", "Ord_Code") REFERENCES "OrderFile" ("Group_ID", "Ord_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderNameList" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_D_Ry" ADD FOREIGN KEY ("Group_ID", "D_Code", "Ko_Code") REFERENCES "w_D_Ko" ("Group_ID", "D_Code", "Ko_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_D_Ry_s" ADD FOREIGN KEY ("Group_ID", "D_Code", "Ko_Code", "Ry_Code") REFERENCES "w_D_Ry" ("Group_ID", "D_Code", "Ko_Code", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_D_Ry_s" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_D_Ry_s" ADD FOREIGN KEY ("Group_ID", "LocalCode", "tan_cd") REFERENCES "tan_m" ("Group_ID", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ko_Lib_Ry" ADD FOREIGN KEY ("Group_ID", "Ko_Code") REFERENCES "Ko_Lib" ("Group_ID", "Ko_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ko_Lib_Ry_s" ADD FOREIGN KEY ("Group_ID", "Ko_Code", "Ry_Code") REFERENCES "w_Ko_Lib_Ry" ("Group_ID", "Ko_Code", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ko_Lib_Ry_s" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ko_Lib_Ry_s" ADD FOREIGN KEY ("Group_ID", "LocalCode", "tan_cd") REFERENCES "tan_m" ("Group_ID", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ry_Lib_s" ADD FOREIGN KEY ("Group_ID", "Ry_Code") REFERENCES "w_Ry_Lib" ("Group_ID", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ry_Lib_s" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ry_Lib_s" ADD FOREIGN KEY ("Group_ID", "LocalCode", "tan_cd") REFERENCES "tan_m" ("Group_ID", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_OrderData" ADD FOREIGN KEY ("Group_ID", "LocalCode") REFERENCES "Zmst" ("Group_ID", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_OrderData" ADD FOREIGN KEY ("Group_ID", "LocalCode", "tan_cd") REFERENCES "tan_m" ("Group_ID", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_OrderGroup" ADD FOREIGN KEY ("Group_ID", "D_Code") REFERENCES "Diary" ("Group_ID", "D_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_ParsonCount" ADD FOREIGN KEY ("Group_ID", "Pro_Code") REFERENCES "ProvideMeal" ("Group_ID", "Pro_Code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_ParsonCountHT" ADD FOREIGN KEY ("Group_ID", "Pro_Code") REFERENCES "ProvideMeal" ("Group_ID", "Pro_Code") DEFERRABLE INITIALLY IMMEDIATE;
