CREATE TABLE "Zmst" (
  "tenant_code" uuid,
  "Z_code" varchar,
  "LocalCode" integer,
  "gun_cd" integer,
  "Tou_cd" integer,
  "Zin_cd" integer,
  "Z_name" varchar,
  "D_S" integer,
  "lss" float,
  "Enj" float,
  "Ene" float,
  "Wat" float,
  "Ami" float,
  "Pro" float,
  "Tri" float,
  "Cho" float,
  "Lip" float,
  "Fac" float,
  "Sat" float,
  "Mon" float,
  "Pol" float,
  "Pn3" float,
  "Pn6" float,
  "Ara" float,
  "Epa" float,
  "Dha" float,
  "Vlm" float,
  "Cvl" float,
  "Vld" float,
  "Tot" float,
  "Ply" float,
  "Car" float,
  "Ora" float,
  "Ash" float,
  "Nat" float,
  "Kal" float,
  "Cal" float,
  "Mag" float,
  "Pho" float,
  "Iro" float,
  "Zin" float,
  "Cop" float,
  "Man" float,
  "Iod" float,
  "Sel" float,
  "Chr" float,
  "Mol" float,
  "Ret" float,
  "Caa" float,
  "Cab" float,
  "Cry" float,
  "Bca" float,
  "Ere" float,
  "ViD" float,
  "ToA" float,
  "ToB" float,
  "ToG" float,
  "ToD" float,
  "ViK" float,
  "VB1" float,
  "VB2" float,
  "Nia" float,
  "Eni" float,
  "VB6" float,
  "B12" float,
  "Fol" float,
  "Pan" float,
  "Bio" float,
  "ViC" float,
  "Alc" float,
  "Esa" float,
  "Wca" float,
  "Txt" text,
  "deleted" integer,
  "locked_by" uuid,
  "locked_at" timestamp,
  "Update_at" timestamp,
  PRIMARY KEY ("tenant_code", "LocalCode")
);

CREATE TABLE "tan_m" (
  "tenant_code" uuid,
  "Z_Code" varchar,
  "LocalCode" integer,
  "tan_cd" integer,
  "tan_Name" varchar,
  "jun" float,
  "jyuuryou" float,
  PRIMARY KEY ("tenant_code", "LocalCode", "tan_cd")
);

CREATE TABLE "Ry_lib" (
  "tenant_code" uuid,
  "Ry_Code" uuid,
  "Name" varchar,
  "Type" integer,
  "Update_at" timestamp,
  "Parent" uuid,
  "Ninzu" integer DEFAULT 1,
  "Ry_note" text,
  "locked_by" uuid,
  "locked_at" timestamp,
  PRIMARY KEY ("tenant_code", "Ry_Code")
);

CREATE TABLE "Ry_lib_s" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "Ry_Code" uuid,
  "LocalCode" integer,
  "sort_no" integer,
  "Z_code" varchar,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer,
  PRIMARY KEY ("id", "tenant_code", "Ry_Code")
);

CREATE TABLE "Ko_Lib" (
  "tenant_code" uuid,
  "Ko_Code" uuid,
  "Name" varchar,
  "Update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  "locked_by" uuid,
  "locked_at" timestamp,
  PRIMARY KEY ("tenant_code", "Ko_Code")
);

CREATE TABLE "Ko_Lib_Ry" (
  "tenant_code" uuid,
  "Ko_Code" uuid,
  "sort_no" integer,
  "Ry_Code" uuid,
  "M_code" integer,
  "Name" varchar,
  "Ninzu" integer DEFAULT 1,
  "update_at" timestamp,
  "Rymemo" text,
  PRIMARY KEY ("tenant_code", "Ko_Code", "Ry_Code")
);

CREATE TABLE "Ko_Lib_Ry_s" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "Ko_Code" uuid,
  "Ry_Code" uuid,
  "M_code" uuid,
  "sort_no" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer,
  PRIMARY KEY ("id", "tenant_code", "Ko_Code", "Ry_Code")
);

CREATE TABLE "Diary" (
  "tenant_code" uuid,
  "D_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  "SelectDay" timestamp,
  PRIMARY KEY ("tenant_code", "D_Code")
);

CREATE TABLE "D_Ko" (
  "tenant_code" uuid,
  "D_Code" uuid,
  "Ko_Day" timestamp,
  "D_Ko_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  PRIMARY KEY ("tenant_code", "D_Code", "D_Ko_Code")
);

CREATE TABLE "D_Ry" (
  "tenant_code" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "M_code" integer,
  "sort_no" integer,
  "D_Ry_Code" uuid,
  "Name" varchar,
  "Ninzu" integer,
  "Rymemo" text,
  "update_at" timestamp,
  PRIMARY KEY ("tenant_code", "D_Code", "Ko_Code", "D_Ry_Code")
);

CREATE TABLE "D_Ry_s" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "M_code" integer,
  "D_Ry_Code" uuid,
  "sort_no" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer,
  PRIMARY KEY ("id", "tenant_code", "D_Code", "Ko_Code", "D_Ry_Code")
);

CREATE TABLE "ProvideMeal" (
  "tenant_code" uuid,
  "Pro_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  "D_Code" uuid,
  "Parcent" float,
  "locked_by" uuid,
  "locked_at" timestamp,
  PRIMARY KEY ("tenant_code", "Pro_Code")
);

CREATE TABLE "GroupIB" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "Pro_Code" uuid,
  "Nutrition" varchar,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float,
  PRIMARY KEY ("id", "tenant_code", "Pro_Code")
);

CREATE TABLE "ParsonCount" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "Pro_Code" uuid,
  "Ko_Day" timestamp,
  "M_code" integer,
  "type" integer,
  "Count" integer,
  PRIMARY KEY ("id", "tenant_code", "Pro_Code")
);

CREATE TABLE "Groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "Pro_Code" uuid,
  "Jun" integer,
  "age" integer,
  "sex" integer,
  "mens" integer,
  "preg" integer,
  "ActivityLevel" integer,
  "ParsonCount" integer,
  PRIMARY KEY ("id", "tenant_code", "Pro_Code")
);

CREATE TABLE "Meal" (
  "tenant_code" uuid,
  "M_Code" integer,
  "Sort_No" integer,
  "Name" varchar
);

CREATE TABLE "OrderFile" (
  "tenant_code" uuid,
  "Ord_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "InstName" varchar,
  "Zip" varchar,
  "Add" varchar,
  "Tel" varchar,
  "Fax" varchar,
  "locked_by" uuid,
  "locked_at" timestamp,
  PRIMARY KEY ("tenant_code", "Ord_Code")
);

CREATE TABLE "OrderGroup" (
  "tenant_code" uuid,
  "Ord_Code" uuid,
  "D_Code" uuid,
  PRIMARY KEY ("tenant_code", "Ord_Code", "D_Code")
);

CREATE TABLE "Dealers" (
  "tenant_code" uuid,
  "Ord_Code" uuid,
  "Deal_Code" integer,
  "Deal_Name" varchar,
  "t_name" varchar,
  "yuubin" varchar,
  "add1" varchar,
  "add2" varchar,
  "tel" varchar,
  "fax" varchar,
  "stop" integer,
  PRIMARY KEY ("tenant_code", "Ord_Code", "Deal_Code")
);

CREATE TABLE "OrderData" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "Ord_Code" uuid,
  "Pro_Code" uuid,
  "D_Code" uuid,
  "Ko_Day" uuid,
  "M_Code" integer,
  "Z_Code" varchar,
  "LocalCode" integer,
  "OrderName" varchar,
  "Deal_Code" integer,
  "UserOrder" float,
  "StaffOrder" float,
  "tan_cd" integer,
  "DeliveryDate" timestamp,
  PRIMARY KEY ("id", "tenant_code", "Ord_Code", "Pro_Code", "D_Code", "Ko_Day")
);

CREATE TABLE "OrderNameList" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "Ord_Code" uuid,
  "ONm_Code" integer,
  "Z_Code" varchar,
  "LocalCode" integer,
  "OrderName" varchar,
  PRIMARY KEY ("id", "tenant_code", "Ord_Code", "ONm_Code")
);

CREATE TABLE "w_CalcData" (
  "tenant_code" uuid,
  "D_Code" uuid,
  "D_Name" varchar,
  "K_Code" uuid,
  "K_Name" varchar,
  "K_Day" timestamp,
  "RSort_no" int,
  "M_Code" int,
  "MealName" varchar,
  "R_Code" uuid,
  "R_Name" varchar,
  "ZSort_no" int,
  "Z_Code" varchar,
  "LocalCode" int,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" int,
  "TanSyoumi" float,
  "TanJunbi" float
);

CREATE TABLE "w_GroupIB" (
  "tenant_code" uuid,
  "Pro_Code" uuid,
  "Jun" integer,
  "Nutrition" varchar,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float,
  "ParsonCount" integer
);

CREATE TABLE "w_CalcDataRymemo" (
  "tenant_code" uuid,
  "D_Code" uuid,
  "D_Name" varchar,
  "Ko_Code" uuid,
  "Ko_Name" varchar,
  "Ko_Day" timestamp,
  "RSort_no" int,
  "M_Code" integer,
  "MealName" varchar,
  "Ry_Code" uuid,
  "Ry_Name" varchar,
  "Rymemo" varchar
);

CREATE TABLE "w_CalcOrderJyunbi" (
  "tenant_code" uuid,
  "Ord_Code" uuid,
  "Ko_Day" timestamp,
  "Z_Code" varchar,
  "LocalCode" integer,
  "UserJyunbi" float,
  "StaffJyunbi" float
);

CREATE TABLE "w_chg_zai" (
  "tenant_code" uuid,
  "Z_Code" varchar,
  "LocalCode" integer,
  "lss" float,
  "Wca" float,
  "EditUserID" uuid,
  "Update_at" timestamp
);

CREATE TABLE "w_D_Ko" (
  "tenant_code" uuid,
  "D_Code" uuid,
  "Ko_Day" timestamp,
  "Ko_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  PRIMARY KEY ("tenant_code", "D_Code", "Ko_Code")
);

CREATE TABLE "w_D_Ry" (
  "tenant_code" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "sort_no" int,
  "Ry_Code" uuid,
  "M_Code" int,
  "Name" varchar,
  "Ninzu" int,
  "update_at" timestamp,
  "Rymemo" varchar,
  PRIMARY KEY ("tenant_code", "D_Code", "Ko_Code", "Ry_Code")
);

CREATE TABLE "w_D_Ry_s" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "M_Code" int,
  "Ry_Code" uuid,
  "sort_no" int,
  "Z_code" varchar,
  "LocalCode" int,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" int,
  PRIMARY KEY ("id", "tenant_code", "D_Code", "Ko_Code", "Ry_Code")
);

CREATE TABLE "w_Grid_Ry_s" (
  "tenant_code" uuid,
  "D_Code" uuid,
  "Ko_Code" uuid,
  "M_Code" integer,
  "meal_sort" integer,
  "Ry_Code" uuid,
  "ry_sort" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "z_sort" integer,
  "Syoumi" float,
  "tan_cd" integer
);

CREATE TABLE "w_Ko_Lib" (
  "tenant_code" uuid,
  "Ko_Code" uuid,
  "Name" varchar,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  PRIMARY KEY ("tenant_code", "Ko_Code")
);

CREATE TABLE "w_Ko_Lib_Ry" (
  "tenant_code" uuid,
  "Ko_Code" uuid,
  "sort_no" integer,
  "Ry_Code" uuid,
  "M_Code" integer,
  "Name" varchar,
  "Ninzu" integer,
  "update_at" timestamp,
  "Rymemo" text,
  PRIMARY KEY ("tenant_code", "Ko_Code", "Ry_Code")
);

CREATE TABLE "w_Ko_Lib_Ry_s" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "Ko_Code" uuid,
  "M_Code" integer,
  "Ry_Code" uuid,
  "sort_no" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer,
  PRIMARY KEY ("id", "tenant_code", "Ko_Code", "Ry_Code")
);

CREATE TABLE "w_Ry_Lib" (
  "tenant_code" uuid,
  "Ry_Code" uuid,
  "Name" varchar,
  "Ninzu" integer,
  "update_at" timestamp,
  "Type" integer,
  "Parent" uuid,
  "Rymemo" text,
  PRIMARY KEY ("tenant_code", "Ry_Code")
);

CREATE TABLE "w_Ry_Lib_s" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "tenant_code" uuid,
  "Ry_Code" uuid,
  "sort_no" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "Syoumi" float,
  "Junbi" float,
  "tan_cd" integer,
  PRIMARY KEY ("id", "tenant_code", "Ry_Code")
);

CREATE TABLE "w_OrderData" (
  "id" int,
  "tenant_code" uuid,
  "Ord_Code" uuid,
  "Pro_Code" uuid,
  "ko_Day" timestamp,
  "M_Code" integer,
  "Jun" integer,
  "Z_code" varchar,
  "LocalCode" integer,
  "OrderName" varchar,
  "UserJyunbi" float,
  "StaffJyunbi" float,
  "Deal_Code" uuid,
  "UserOrder" float,
  "StaffOrder" float,
  "tan_cd" integer,
  "DeliveryDate" timestamp,
  PRIMARY KEY ("id", "tenant_code", "Ord_Code", "Pro_Code", "ko_Day")
);

CREATE TABLE "w_OrderGroup" (
  "tenant_code" uuid,
  "Ord_Code" uuid,
  "D_Code" uuid,
  PRIMARY KEY ("tenant_code", "Ord_Code", "D_Code")
);

CREATE TABLE "w_ParsonCount" (
  "tenant_code" uuid,
  "Pro_Code" uuid,
  "Ko_Day" timestamp,
  "M_Code" integer,
  "type" integer,
  "Count" integer,
  PRIMARY KEY ("tenant_code", "Pro_Code", "Ko_Day", "M_Code")
);

CREATE TABLE "w_ParsonCountHT" (
  "tenant_code" uuid,
  "Ord_Code" uuid,
  "Pro_Code" uuid,
  "Ko_Day" timestamp,
  "M_Code" integer,
  "type" integer,
  "Count" integer,
  PRIMARY KEY ("tenant_code", "Ord_Code", "Pro_Code", "Ko_Day", "M_Code")
);

CREATE TABLE "GenerationsItem" (
  "ID" integer PRIMARY KEY,
  "Generation" varchar,
  "OlderMin" integer,
  "OlderMax" integer
);

CREATE TABLE "ActivityLevel" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "activityLevel" int,
  "preg" int,
  "Val" float
);

CREATE TABLE "ActLevel" (
  "ActivityLevel" int,
  "ActivityVal" int,
  "Oldermin" int,
  "Oldermax" int,
  "AVmin" int,
  "AVmax" int,
  "Combo" varchar,
  "PrtCaption" varchar,
  "caption" varchar
);

CREATE TABLE "BaseWeightC" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "a" float,
  "b" float
);

CREATE TABLE "BMStandardVal" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "preg" int,
  "BMBase" float,
  "Val" float
);

CREATE TABLE "gun_m" (
  "tenant_code" uuid,
  "jun" int,
  "dai_cd" int,
  "dai_name" varchar,
  "syou_cd" int,
  "syou_name" varchar
);

CREATE TABLE "ColName" (
  "tenant_code" uuid,
  "No" INT GENERATED BY DEFAULT AS IDENTITY,
  "SortNo" int,
  "Col" varchar,
  "Name" varchar,
  "Format" varchar,
  "Digit" int,
  "Visible" boolean,
  "Nutrition" boolean,
  "PName1" varchar,
  "PName2" varchar,
  "PName3" varchar,
  "PTanni" varchar,
  PRIMARY KEY ("tenant_code", "No")
);

CREATE TABLE "IBColName" (
  "tenant_code" uuid,
  "No" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "SortNo" integer,
  "Col" varchar,
  "egNpCol" varchar,
  "Name" varchar,
  "Format" varchar,
  "Digit" integer,
  "ForEnergy" integer,
  "Visible" boolean,
  "PName1" varchar,
  "PName2" varchar,
  "PName3" varchar,
  "PTanni" varchar,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float,
  "PregCalc" integer,
  PRIMARY KEY ("tenant_code", "No")
);

CREATE TABLE "IncWeight" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "Val" float
);

CREATE TABLE "PregItem" (
  "Preg" int PRIMARY KEY,
  "Caption" varchar
);

CREATE TABLE "ProBase" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "C" float,
  "E" float,
  "F" float,
  "G" float
);

CREATE TABLE "StoreUpEnergy" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "DeEnergy" float,
  "UpEnergy" float
);

CREATE TABLE "Ene" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Pro" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ProEne" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Lip" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Sat" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Car" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Tot" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Ere" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ViD" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ToA" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ViK" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "VB1" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "VB2" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Nia" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "VB6" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "B12" (
  "older_min" int,
  "older_max" int,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Fol" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Pan" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Bio" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ViC" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Nat" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Esa" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Kal" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Cal" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Mag" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Pho" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Iro" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Zin" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Cop" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Man" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Iod" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Sel" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Chr" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Mol" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE INDEX "idx_ry_s_parent" ON "Ry_lib_s" ("tenant_code", "Ry_Code");

CREATE INDEX "idx_ry_s_zmst" ON "Ry_lib_s" ("tenant_code", "LocalCode", "tan_cd");

CREATE INDEX "idx_Ko_lib_ry_parent" ON "Ko_Lib_Ry" ("tenant_code", "Ko_Code");

CREATE INDEX "idx_Ko_Lib_ry_s_parent" ON "Ko_Lib_Ry_s" ("tenant_code", "Ko_Code", "Ry_Code");

CREATE INDEX "idx_Ko_Lib_ry_s_zmst" ON "Ko_Lib_Ry_s" ("tenant_code", "LocalCode", "tan_cd");

CREATE INDEX "idx_D_Ko_parent" ON "D_Ko" ("tenant_code", "D_Code");

CREATE INDEX "idx_D_Ry_parent" ON "D_Ry" ("tenant_code", "D_Code", "Ko_Code");

CREATE INDEX "idx_D_Ry_s_parent" ON "D_Ry_s" ("tenant_code", "D_Code", "Ko_Code", "D_Ry_Code");

CREATE INDEX "idx_D_Ry_s_zmst" ON "D_Ry_s" ("tenant_code", "LocalCode", "tan_cd");

CREATE INDEX "idx_GroupIB_ProvideMeal" ON "GroupIB" ("tenant_code", "Pro_Code");

CREATE INDEX "idx_ParsonCount_ProvideMeal" ON "ParsonCount" ("tenant_code", "Pro_Code");

CREATE INDEX "idx_OrderData_OrderFile" ON "OrderData" ("tenant_code", "Ord_Code", "Pro_Code", "D_Code", "Ko_Day");

CREATE INDEX "idx_OrderNameList_OrderFile" ON "OrderNameList" ("tenant_code", "Ord_Code");

COMMENT ON COLUMN "Zmst"."LocalCode" IS 'システム固有ID';

COMMENT ON COLUMN "Zmst"."D_S" IS '動物性植物性';

COMMENT ON COLUMN "Zmst"."lss" IS '廃棄率';

COMMENT ON COLUMN "Zmst"."Enj" IS 'エネルギーKj';

COMMENT ON COLUMN "Zmst"."Ene" IS 'エネルギーkcal';

COMMENT ON COLUMN "Zmst"."Wat" IS '水分';

COMMENT ON COLUMN "Zmst"."Ami" IS 'アミノ酸組成によるたんぱく質';

COMMENT ON COLUMN "Zmst"."Pro" IS 'たんぱく質';

COMMENT ON COLUMN "Zmst"."Tri" IS 'トリアシルグリセロール当量';

COMMENT ON COLUMN "Zmst"."Cho" IS 'コレステロール';

COMMENT ON COLUMN "Zmst"."Lip" IS '脂質';

COMMENT ON COLUMN "Zmst"."Fac" IS '脂肪酸総量';

COMMENT ON COLUMN "Zmst"."Sat" IS '飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Mon" IS '一価不飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Pol" IS '多価不飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Pn3" IS 'N3系多価不飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Pn6" IS 'N6系多価不飽和脂肪酸';

COMMENT ON COLUMN "Zmst"."Ara" IS 'アラキドン酸';

COMMENT ON COLUMN "Zmst"."Epa" IS 'イコサペンタエン酸';

COMMENT ON COLUMN "Zmst"."Dha" IS 'ドコサヘキサエン酸';

COMMENT ON COLUMN "Zmst"."Vlm" IS '利用可能炭水化物単糖当量';

COMMENT ON COLUMN "Zmst"."Cvl" IS '重量計利用可能炭水化物';

COMMENT ON COLUMN "Zmst"."Vld" IS '差引法利用可能炭水化物';

COMMENT ON COLUMN "Zmst"."Tot" IS '食物繊維総量';

COMMENT ON COLUMN "Zmst"."Ply" IS '糖アルコール';

COMMENT ON COLUMN "Zmst"."Car" IS '炭水化物';

COMMENT ON COLUMN "Zmst"."Ora" IS '有機酸';

COMMENT ON COLUMN "Zmst"."Ash" IS '灰分';

COMMENT ON COLUMN "Zmst"."Nat" IS 'ナトリウム';

COMMENT ON COLUMN "Zmst"."Kal" IS 'カリウム';

COMMENT ON COLUMN "Zmst"."Cal" IS 'カルシウム';

COMMENT ON COLUMN "Zmst"."Mag" IS 'マグネシウム';

COMMENT ON COLUMN "Zmst"."Pho" IS 'リン';

COMMENT ON COLUMN "Zmst"."Iro" IS '鉄';

COMMENT ON COLUMN "Zmst"."Zin" IS '亜鉛';

COMMENT ON COLUMN "Zmst"."Cop" IS '銅';

COMMENT ON COLUMN "Zmst"."Man" IS 'マンガン';

COMMENT ON COLUMN "Zmst"."Iod" IS 'ヨウ素';

COMMENT ON COLUMN "Zmst"."Sel" IS 'セレン';

COMMENT ON COLUMN "Zmst"."Chr" IS 'クロム';

COMMENT ON COLUMN "Zmst"."Mol" IS 'モリブデン';

COMMENT ON COLUMN "Zmst"."Ret" IS 'レチノール';

COMMENT ON COLUMN "Zmst"."Caa" IS 'αカロテン';

COMMENT ON COLUMN "Zmst"."Cab" IS 'βカロテン';

COMMENT ON COLUMN "Zmst"."Cry" IS 'βクリプトキサンチン';

COMMENT ON COLUMN "Zmst"."Bca" IS 'βカロテン当量';

COMMENT ON COLUMN "Zmst"."Ere" IS 'レチノール活性当量';

COMMENT ON COLUMN "Zmst"."ViD" IS 'ビタミンD';

COMMENT ON COLUMN "Zmst"."ToA" IS 'αトコフェロール';

COMMENT ON COLUMN "Zmst"."ToB" IS 'βトコフェロール';

COMMENT ON COLUMN "Zmst"."ToG" IS 'γトコフェロール';

COMMENT ON COLUMN "Zmst"."ToD" IS 'δトコフェロール';

COMMENT ON COLUMN "Zmst"."ViK" IS 'ビタミンK';

COMMENT ON COLUMN "Zmst"."VB1" IS 'ビタミンB1';

COMMENT ON COLUMN "Zmst"."VB2" IS 'ビタミンB2';

COMMENT ON COLUMN "Zmst"."Nia" IS 'ナイアシン';

COMMENT ON COLUMN "Zmst"."Eni" IS 'ナイアシン当量';

COMMENT ON COLUMN "Zmst"."VB6" IS 'ビタミンB6';

COMMENT ON COLUMN "Zmst"."B12" IS 'ビタミンB12';

COMMENT ON COLUMN "Zmst"."Fol" IS '葉酸';

COMMENT ON COLUMN "Zmst"."Pan" IS 'パントテン酸';

COMMENT ON COLUMN "Zmst"."Bio" IS 'ビオチン';

COMMENT ON COLUMN "Zmst"."ViC" IS 'ビタミンC';

COMMENT ON COLUMN "Zmst"."Alc" IS 'アルコール';

COMMENT ON COLUMN "Zmst"."Esa" IS '食塩相当量';

COMMENT ON COLUMN "Zmst"."Wca" IS '重量変化率';

COMMENT ON COLUMN "Zmst"."Txt" IS '備考';

COMMENT ON COLUMN "Zmst"."locked_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "Zmst"."Update_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "Ry_lib"."Type" IS '0:献立 / 1:フォルダ';

COMMENT ON COLUMN "Ry_lib"."Parent" IS '親フォルダのRy_Code';

COMMENT ON COLUMN "Ry_lib"."locked_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "Ry_lib_s"."Syoumi" IS '正味重量';

COMMENT ON COLUMN "Ry_lib_s"."Junbi" IS '準備重量';

COMMENT ON COLUMN "Ko_Lib"."Type" IS '0:献立 / 1:フォルダ';

COMMENT ON COLUMN "Ko_Lib"."locked_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "Ko_Lib_Ry_s"."id" IS 'レコードが一意になる様オートナンバー型を設定、これが無いとソート番号の入れ替えが出来ない';

COMMENT ON COLUMN "Diary"."Parent" IS '格納フォルダ';

COMMENT ON COLUMN "Diary"."SelectDay" IS '閉じる前に最後に選択された日';

COMMENT ON COLUMN "D_Ko"."D_Code" IS 'DiaryテーブルのID';

COMMENT ON COLUMN "D_Ko"."Ko_Day" IS 'timestamptz(6)';

COMMENT ON COLUMN "D_Ry"."D_Code" IS 'カレンダーID';

COMMENT ON COLUMN "D_Ry"."Ko_Code" IS '献立Code';

COMMENT ON COLUMN "D_Ry"."D_Ry_Code" IS '料理マスターCode';

COMMENT ON COLUMN "D_Ry"."Name" IS '実行時の料理名';

COMMENT ON COLUMN "D_Ry"."Ninzu" IS 'その日の人数';

COMMENT ON TABLE "D_Ry_s" IS 'ここをSUMして、Zmstの栄養価を掛ける。220万回のドラマがここに。';

COMMENT ON COLUMN "D_Ry_s"."D_Code" IS 'カレンダーID';

COMMENT ON COLUMN "D_Ry_s"."Ko_Code" IS '献立Code';

COMMENT ON COLUMN "D_Ry_s"."D_Ry_Code" IS 'D_Ryとの紐付け';

COMMENT ON COLUMN "D_Ry_s"."Z_code" IS '材料コード';

COMMENT ON COLUMN "D_Ry_s"."LocalCode" IS '旧PecNo';

COMMENT ON COLUMN "D_Ry_s"."Syoumi" IS '実行時の正味重量';

COMMENT ON COLUMN "D_Ry_s"."Junbi" IS '実行時の準備重量';

COMMENT ON COLUMN "ProvideMeal"."D_Code" IS '対象となるDiary（グループ）';

COMMENT ON COLUMN "ProvideMeal"."Parcent" IS '一日当りの栄養給与提供（%）１食の提供（１日分の食事を提供しない施設向け）';

COMMENT ON COLUMN "ProvideMeal"."locked_at" IS 'timestamptz(6)';

COMMENT ON TABLE "GroupIB" IS '食種ごとの栄養基準マッピング';

COMMENT ON TABLE "ParsonCount" IS '日々の提供食数';

COMMENT ON COLUMN "ParsonCount"."type" IS '利用者：職員';

COMMENT ON TABLE "Groups" IS '対象集団の属性定義';

COMMENT ON TABLE "Meal" IS '食事区分';

COMMENT ON TABLE "OrderFile" IS '発注データ。および発注書のヘッダー情報';

COMMENT ON COLUMN "OrderFile"."locked_at" IS 'timestamptz(6)';

COMMENT ON TABLE "OrderGroup" IS 'OrderFileに対してどのDiaryが紐づいているか';

COMMENT ON TABLE "Dealers" IS '業者マスタ';

COMMENT ON COLUMN "Dealers"."t_name" IS '担当者名';

COMMENT ON COLUMN "Dealers"."stop" IS '取引停止フラグ';

COMMENT ON TABLE "OrderData" IS '発注明細。材料×人数×端数処理の結果';

COMMENT ON COLUMN "OrderData"."DeliveryDate" IS '納入日';

COMMENT ON TABLE "OrderNameList" IS '材料呼称変換,全発注書データ共通';

COMMENT ON COLUMN "w_CalcData"."Junbi" IS 'gで保存すること';

COMMENT ON COLUMN "w_CalcData"."tan_cd" IS '印刷時など、状況に応じて使うこと';

COMMENT ON COLUMN "w_CalcData"."TanSyoumi" IS '単位数量で保存';

COMMENT ON COLUMN "w_CalcData"."TanJunbi" IS '単位数量で保存';

COMMENT ON COLUMN "w_GroupIB"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "w_GroupIB"."RDA" IS '推奨量';

COMMENT ON COLUMN "w_GroupIB"."AI" IS '目安量';

COMMENT ON COLUMN "w_GroupIB"."UL" IS '耐容上限量';

COMMENT ON COLUMN "w_GroupIB"."DG" IS '目安量';

COMMENT ON COLUMN "w_GroupIB"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "w_CalcDataRymemo"."Rymemo" IS '長いテキスト';

COMMENT ON COLUMN "w_chg_zai"."Update_at" IS 'timestamptz(6)';

COMMENT ON COLUMN "w_D_Ko"."D_Code" IS 'DiaryテーブルのID';

COMMENT ON COLUMN "w_D_Ko"."Ko_Day" IS '献立の日付';

COMMENT ON COLUMN "w_D_Ry"."Ry_Code" IS '料理識別コード';

COMMENT ON COLUMN "w_D_Ry"."M_Code" IS '食事';

COMMENT ON COLUMN "w_D_Ry"."Name" IS '料理名';

COMMENT ON COLUMN "w_D_Ry"."Rymemo" IS '長いテキスト';

COMMENT ON COLUMN "w_Ko_Lib"."Type" IS '0:献立カレンダー / 1:フォルダ';

COMMENT ON COLUMN "w_Ko_Lib"."Parent" IS '格納フォルダ (再帰リレーション用)';

COMMENT ON COLUMN "w_Ko_Lib_Ry"."Ry_Code" IS '料理識別コード';

COMMENT ON COLUMN "w_Ko_Lib_Ry"."M_Code" IS '食事';

COMMENT ON COLUMN "w_Ko_Lib_Ry"."Name" IS '料理名';

COMMENT ON COLUMN "w_Ry_Lib"."Parent" IS '格納フォルダ';

COMMENT ON TABLE "GenerationsItem" IS '世代・年齢区分マスター';

COMMENT ON COLUMN "ActivityLevel"."older_min" IS '年齢別の活動レベル（下限）';

COMMENT ON COLUMN "ActLevel"."ActivityLevel" IS '身体活動区分';

COMMENT ON COLUMN "ActLevel"."ActivityVal" IS '身体活動レベル代表値';

COMMENT ON COLUMN "ActLevel"."Oldermin" IS '対象年齢下限';

COMMENT ON COLUMN "ActLevel"."Oldermax" IS '対象年齢上限';

COMMENT ON COLUMN "ActLevel"."AVmin" IS '身体活動レベル下限';

COMMENT ON COLUMN "ActLevel"."AVmax" IS '身体活動レベル上限';

COMMENT ON COLUMN "ActLevel"."Combo" IS 'コンボボックス用';

COMMENT ON COLUMN "ActLevel"."caption" IS '説明';

COMMENT ON COLUMN "BaseWeightC"."a" IS '推定平均必要量';

COMMENT ON COLUMN "BaseWeightC"."b" IS '推奨量';

COMMENT ON COLUMN "BMStandardVal"."older_min" IS '表6の数値';

COMMENT ON COLUMN "BMStandardVal"."BMBase" IS '基礎代謝基準値(kcal/体重kg/日)';

COMMENT ON COLUMN "BMStandardVal"."Val" IS '基礎代謝量(kcal)=基礎代謝基準値＊参照体重 1の位切り上げ';

COMMENT ON COLUMN "ColName"."No" IS 'オートナンバー型';

COMMENT ON COLUMN "IBColName"."No" IS 'オートナンバー型';

COMMENT ON COLUMN "IBColName"."SortNo" IS '並び順';

COMMENT ON COLUMN "IBColName"."Col" IS '列識別子';

COMMENT ON COLUMN "IBColName"."Name" IS '項目名称';

COMMENT ON COLUMN "IBColName"."Format" IS '表示書式';

COMMENT ON COLUMN "IBColName"."Digit" IS '桁数';

COMMENT ON COLUMN "IBColName"."Visible" IS '表示フラグ';

COMMENT ON COLUMN "IBColName"."PTanni" IS '単位';

COMMENT ON COLUMN "IBColName"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "IBColName"."RDA" IS '推奨量';

COMMENT ON COLUMN "IBColName"."AI" IS '目安量（0=目標, 1=目標未満, 2=目標以上, 3=目標以上 目標未満）';

COMMENT ON COLUMN "IBColName"."UL" IS '耐容上限量';

COMMENT ON COLUMN "IBColName"."DG" IS '目標量';

COMMENT ON COLUMN "IBColName"."PregCalc" IS '妊婦数値計算フラグ（0=加算, 1=交換）';

COMMENT ON COLUMN "IncWeight"."older_min" IS '表10';

COMMENT ON COLUMN "IncWeight"."Val" IS '体重増加量(kg/年)';

COMMENT ON COLUMN "ProBase"."C" IS '体たんぱく質(%)';

COMMENT ON COLUMN "ProBase"."E" IS '蓄積効率(%)';

COMMENT ON COLUMN "ProBase"."F" IS '維持必要量';

COMMENT ON COLUMN "ProBase"."G" IS '利用効率(%)';

COMMENT ON COLUMN "StoreUpEnergy"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "StoreUpEnergy"."DeEnergy" IS 'エネルギー密度(kcal／g)';

COMMENT ON COLUMN "StoreUpEnergy"."UpEnergy" IS 'エネルギー蓄積量(kcal／日)';

COMMENT ON COLUMN "Ene"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Ene"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Ene"."RDA" IS '推奨量';

COMMENT ON COLUMN "Ene"."AI" IS '目安量';

COMMENT ON COLUMN "Ene"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Ene"."DG" IS '目安量';

COMMENT ON COLUMN "Ene"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Pro"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Pro"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Pro"."RDA" IS '推奨量';

COMMENT ON COLUMN "Pro"."AI" IS '目安量';

COMMENT ON COLUMN "Pro"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Pro"."DG" IS '目安量';

COMMENT ON COLUMN "Pro"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ProEne"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ProEne"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ProEne"."RDA" IS '推奨量';

COMMENT ON COLUMN "ProEne"."AI" IS '目安量';

COMMENT ON COLUMN "ProEne"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ProEne"."DG" IS '目安量';

COMMENT ON COLUMN "ProEne"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Lip"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Lip"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Lip"."RDA" IS '推奨量';

COMMENT ON COLUMN "Lip"."AI" IS '目安量';

COMMENT ON COLUMN "Lip"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Lip"."DG" IS '目安量';

COMMENT ON COLUMN "Lip"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Sat"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Sat"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Sat"."RDA" IS '推奨量';

COMMENT ON COLUMN "Sat"."AI" IS '目安量';

COMMENT ON COLUMN "Sat"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Sat"."DG" IS '目安量';

COMMENT ON COLUMN "Sat"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Car"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Car"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Car"."RDA" IS '推奨量';

COMMENT ON COLUMN "Car"."AI" IS '目安量';

COMMENT ON COLUMN "Car"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Car"."DG" IS '目安量';

COMMENT ON COLUMN "Car"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Tot"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Tot"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Tot"."RDA" IS '推奨量';

COMMENT ON COLUMN "Tot"."AI" IS '目安量';

COMMENT ON COLUMN "Tot"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Tot"."DG" IS '目安量';

COMMENT ON COLUMN "Tot"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Ere"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Ere"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Ere"."RDA" IS '推奨量';

COMMENT ON COLUMN "Ere"."AI" IS '目安量';

COMMENT ON COLUMN "Ere"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Ere"."DG" IS '目安量';

COMMENT ON COLUMN "Ere"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ViD"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ViD"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ViD"."RDA" IS '推奨量';

COMMENT ON COLUMN "ViD"."AI" IS '目安量';

COMMENT ON COLUMN "ViD"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ViD"."DG" IS '目安量';

COMMENT ON COLUMN "ViD"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ToA"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ToA"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ToA"."RDA" IS '推奨量';

COMMENT ON COLUMN "ToA"."AI" IS '目安量';

COMMENT ON COLUMN "ToA"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ToA"."DG" IS '目安量';

COMMENT ON COLUMN "ToA"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ViK"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ViK"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ViK"."RDA" IS '推奨量';

COMMENT ON COLUMN "ViK"."AI" IS '目安量';

COMMENT ON COLUMN "ViK"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ViK"."DG" IS '目安量';

COMMENT ON COLUMN "ViK"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "VB1"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "VB1"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "VB1"."RDA" IS '推奨量';

COMMENT ON COLUMN "VB1"."AI" IS '目安量';

COMMENT ON COLUMN "VB1"."UL" IS '耐容上限量';

COMMENT ON COLUMN "VB1"."DG" IS '目安量';

COMMENT ON COLUMN "VB1"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "VB2"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "VB2"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "VB2"."RDA" IS '推奨量';

COMMENT ON COLUMN "VB2"."AI" IS '目安量';

COMMENT ON COLUMN "VB2"."UL" IS '耐容上限量';

COMMENT ON COLUMN "VB2"."DG" IS '目安量';

COMMENT ON COLUMN "VB2"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Nia"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Nia"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Nia"."RDA" IS '推奨量';

COMMENT ON COLUMN "Nia"."AI" IS '目安量';

COMMENT ON COLUMN "Nia"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Nia"."DG" IS '目安量';

COMMENT ON COLUMN "Nia"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "VB6"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "VB6"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "VB6"."RDA" IS '推奨量';

COMMENT ON COLUMN "VB6"."AI" IS '目安量';

COMMENT ON COLUMN "VB6"."UL" IS '耐容上限量';

COMMENT ON COLUMN "VB6"."DG" IS '目安量';

COMMENT ON COLUMN "VB6"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "B12"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "B12"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "B12"."RDA" IS '推奨量';

COMMENT ON COLUMN "B12"."AI" IS '目安量';

COMMENT ON COLUMN "B12"."UL" IS '耐容上限量';

COMMENT ON COLUMN "B12"."DG" IS '目安量';

COMMENT ON COLUMN "B12"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Fol"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Fol"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Fol"."RDA" IS '推奨量';

COMMENT ON COLUMN "Fol"."AI" IS '目安量';

COMMENT ON COLUMN "Fol"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Fol"."DG" IS '目安量';

COMMENT ON COLUMN "Fol"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Pan"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Pan"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Pan"."RDA" IS '推奨量';

COMMENT ON COLUMN "Pan"."AI" IS '目安量';

COMMENT ON COLUMN "Pan"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Pan"."DG" IS '目安量';

COMMENT ON COLUMN "Pan"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Bio"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Bio"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Bio"."RDA" IS '推奨量';

COMMENT ON COLUMN "Bio"."AI" IS '目安量';

COMMENT ON COLUMN "Bio"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Bio"."DG" IS '目安量';

COMMENT ON COLUMN "Bio"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ViC"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ViC"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ViC"."RDA" IS '推奨量';

COMMENT ON COLUMN "ViC"."AI" IS '目安量';

COMMENT ON COLUMN "ViC"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ViC"."DG" IS '目安量';

COMMENT ON COLUMN "ViC"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Nat"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Nat"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Nat"."RDA" IS '推奨量';

COMMENT ON COLUMN "Nat"."AI" IS '目安量';

COMMENT ON COLUMN "Nat"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Nat"."DG" IS '目安量';

COMMENT ON COLUMN "Nat"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Esa"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Esa"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Esa"."RDA" IS '推奨量';

COMMENT ON COLUMN "Esa"."AI" IS '目安量';

COMMENT ON COLUMN "Esa"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Esa"."DG" IS '目安量';

COMMENT ON COLUMN "Esa"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Kal"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Kal"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Kal"."RDA" IS '推奨量';

COMMENT ON COLUMN "Kal"."AI" IS '目安量';

COMMENT ON COLUMN "Kal"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Kal"."DG" IS '目安量';

COMMENT ON COLUMN "Kal"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Cal"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Cal"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Cal"."RDA" IS '推奨量';

COMMENT ON COLUMN "Cal"."AI" IS '目安量';

COMMENT ON COLUMN "Cal"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Cal"."DG" IS '目安量';

COMMENT ON COLUMN "Cal"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Mag"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Mag"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Mag"."RDA" IS '推奨量';

COMMENT ON COLUMN "Mag"."AI" IS '目安量';

COMMENT ON COLUMN "Mag"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Mag"."DG" IS '目安量';

COMMENT ON COLUMN "Mag"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Pho"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Pho"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Pho"."RDA" IS '推奨量';

COMMENT ON COLUMN "Pho"."AI" IS '目安量';

COMMENT ON COLUMN "Pho"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Pho"."DG" IS '目安量';

COMMENT ON COLUMN "Pho"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Iro"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Iro"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Iro"."RDA" IS '推奨量';

COMMENT ON COLUMN "Iro"."AI" IS '目安量';

COMMENT ON COLUMN "Iro"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Iro"."DG" IS '目安量';

COMMENT ON COLUMN "Iro"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Zin"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Zin"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Zin"."RDA" IS '推奨量';

COMMENT ON COLUMN "Zin"."AI" IS '目安量';

COMMENT ON COLUMN "Zin"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Zin"."DG" IS '目安量';

COMMENT ON COLUMN "Zin"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Cop"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Cop"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Cop"."RDA" IS '推奨量';

COMMENT ON COLUMN "Cop"."AI" IS '目安量';

COMMENT ON COLUMN "Cop"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Cop"."DG" IS '目安量';

COMMENT ON COLUMN "Cop"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Man"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Man"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Man"."RDA" IS '推奨量';

COMMENT ON COLUMN "Man"."AI" IS '目安量';

COMMENT ON COLUMN "Man"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Man"."DG" IS '目安量';

COMMENT ON COLUMN "Man"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Iod"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Iod"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Iod"."RDA" IS '推奨量';

COMMENT ON COLUMN "Iod"."AI" IS '目安量';

COMMENT ON COLUMN "Iod"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Iod"."DG" IS '目安量';

COMMENT ON COLUMN "Iod"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Sel"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Sel"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Sel"."RDA" IS '推奨量';

COMMENT ON COLUMN "Sel"."AI" IS '目安量';

COMMENT ON COLUMN "Sel"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Sel"."DG" IS '目安量';

COMMENT ON COLUMN "Sel"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Chr"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Chr"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Chr"."RDA" IS '推奨量';

COMMENT ON COLUMN "Chr"."AI" IS '目安量';

COMMENT ON COLUMN "Chr"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Chr"."DG" IS '目安量';

COMMENT ON COLUMN "Chr"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Mol"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Mol"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Mol"."RDA" IS '推奨量';

COMMENT ON COLUMN "Mol"."AI" IS '目安量';

COMMENT ON COLUMN "Mol"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Mol"."DG" IS '目安量';

COMMENT ON COLUMN "Mol"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

ALTER TABLE "tan_m" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ry_lib_s" ADD FOREIGN KEY ("tenant_code", "Ry_Code") REFERENCES "Ry_lib" ("tenant_code", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ry_lib_s" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ry_lib_s" ADD FOREIGN KEY ("tenant_code", "LocalCode", "tan_cd") REFERENCES "tan_m" ("tenant_code", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ko_Lib_Ry" ADD FOREIGN KEY ("tenant_code", "Ko_Code") REFERENCES "Ko_Lib" ("tenant_code", "Ko_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ko_Lib_Ry_s" ADD FOREIGN KEY ("tenant_code", "Ko_Code", "Ry_Code") REFERENCES "Ko_Lib_Ry" ("tenant_code", "Ko_Code", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ko_Lib_Ry_s" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ko_Lib_Ry_s" ADD FOREIGN KEY ("tenant_code", "LocalCode", "tan_cd") REFERENCES "tan_m" ("tenant_code", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ko" ADD FOREIGN KEY ("tenant_code", "D_Code") REFERENCES "Diary" ("tenant_code", "D_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ry" ADD FOREIGN KEY ("tenant_code", "D_Code", "Ko_Code") REFERENCES "D_Ko" ("tenant_code", "D_Code", "D_Ko_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ry_s" ADD FOREIGN KEY ("tenant_code", "D_Code", "Ko_Code", "D_Ry_Code") REFERENCES "D_Ry" ("tenant_code", "D_Code", "Ko_Code", "D_Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ry_s" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "D_Ry_s" ADD FOREIGN KEY ("tenant_code", "LocalCode", "tan_cd") REFERENCES "tan_m" ("tenant_code", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ProvideMeal" ADD FOREIGN KEY ("tenant_code", "D_Code") REFERENCES "Diary" ("tenant_code", "D_Code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GroupIB" ADD FOREIGN KEY ("tenant_code", "Pro_Code") REFERENCES "ProvideMeal" ("tenant_code", "Pro_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ParsonCount" ADD FOREIGN KEY ("tenant_code", "Pro_Code") REFERENCES "ProvideMeal" ("tenant_code", "Pro_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Groups" ADD FOREIGN KEY ("tenant_code", "Pro_Code") REFERENCES "ProvideMeal" ("tenant_code", "Pro_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderGroup" ADD FOREIGN KEY ("tenant_code", "D_Code") REFERENCES "Diary" ("tenant_code", "D_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Dealers" ADD FOREIGN KEY ("tenant_code", "Ord_Code") REFERENCES "OrderFile" ("tenant_code", "Ord_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("tenant_code", "Ord_Code") REFERENCES "OrderFile" ("tenant_code", "Ord_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("tenant_code", "Pro_Code") REFERENCES "ProvideMeal" ("tenant_code", "Pro_Code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("tenant_code", "Ord_Code", "Deal_Code") REFERENCES "Dealers" ("tenant_code", "Ord_Code", "Deal_Code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderData" ADD FOREIGN KEY ("tenant_code", "LocalCode", "tan_cd") REFERENCES "tan_m" ("tenant_code", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderNameList" ADD FOREIGN KEY ("tenant_code", "Ord_Code") REFERENCES "OrderFile" ("tenant_code", "Ord_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderNameList" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_D_Ry" ADD FOREIGN KEY ("tenant_code", "D_Code", "Ko_Code") REFERENCES "w_D_Ko" ("tenant_code", "D_Code", "Ko_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_D_Ry_s" ADD FOREIGN KEY ("tenant_code", "D_Code", "Ko_Code", "Ry_Code") REFERENCES "w_D_Ry" ("tenant_code", "D_Code", "Ko_Code", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_D_Ry_s" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_D_Ry_s" ADD FOREIGN KEY ("tenant_code", "LocalCode", "tan_cd") REFERENCES "tan_m" ("tenant_code", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ko_Lib_Ry" ADD FOREIGN KEY ("tenant_code", "Ko_Code") REFERENCES "Ko_Lib" ("tenant_code", "Ko_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ko_Lib_Ry_s" ADD FOREIGN KEY ("tenant_code", "Ko_Code", "Ry_Code") REFERENCES "w_Ko_Lib_Ry" ("tenant_code", "Ko_Code", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ko_Lib_Ry_s" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ko_Lib_Ry_s" ADD FOREIGN KEY ("tenant_code", "LocalCode", "tan_cd") REFERENCES "tan_m" ("tenant_code", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ry_Lib_s" ADD FOREIGN KEY ("tenant_code", "Ry_Code") REFERENCES "w_Ry_Lib" ("tenant_code", "Ry_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ry_Lib_s" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_Ry_Lib_s" ADD FOREIGN KEY ("tenant_code", "LocalCode", "tan_cd") REFERENCES "tan_m" ("tenant_code", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_OrderData" ADD FOREIGN KEY ("tenant_code", "LocalCode") REFERENCES "Zmst" ("tenant_code", "LocalCode") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_OrderData" ADD FOREIGN KEY ("tenant_code", "LocalCode", "tan_cd") REFERENCES "tan_m" ("tenant_code", "LocalCode", "tan_cd") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_OrderGroup" ADD FOREIGN KEY ("tenant_code", "D_Code") REFERENCES "Diary" ("tenant_code", "D_Code") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_ParsonCount" ADD FOREIGN KEY ("tenant_code", "Pro_Code") REFERENCES "ProvideMeal" ("tenant_code", "Pro_Code") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "w_ParsonCountHT" ADD FOREIGN KEY ("tenant_code", "Pro_Code") REFERENCES "ProvideMeal" ("tenant_code", "Pro_Code") DEFERRABLE INITIALLY IMMEDIATE;
