CREATE TABLE "GenerationsItem" (
  "ID" integer PRIMARY KEY,
  "Generation" varchar,
  "OlderMin" integer,
  "OlderMax" integer
);

CREATE TABLE "ActivityLevel" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "activityLevel" int,
  "preg" int,
  "Val" float
);

CREATE TABLE "ActLevel" (
  "ActivityLevel" int,
  "ActivityVal" int,
  "Oldermin" int,
  "Oldermax" int,
  "AVmin" int,
  "AVmax" int,
  "Combo" varchar,
  "PrtCaption" varchar,
  "caption" varchar
);

CREATE TABLE "BaseWeightC" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "a" float,
  "b" float
);

CREATE TABLE "BMStandardVal" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "preg" int,
  "BMBase" float,
  "Val" float
);

CREATE TABLE "gun_m" (
  "jun" int,
  "dai_cd" int,
  "dai_name" varchar,
  "syou_cd" int,
  "syou_name" varchar
);

CREATE TABLE "ColName" (
  "Group_ID" uuid,
  "No" INT GENERATED BY DEFAULT AS IDENTITY,
  "SortNo" int,
  "Col" varchar,
  "Name" varchar,
  "Format" varchar,
  "Digit" int,
  "Visible" boolean,
  "Nutrition" boolean,
  "PName1" varchar,
  "PName2" varchar,
  "PName3" varchar,
  "PTanni" varchar,
  PRIMARY KEY ("Group_ID", "No")
);

CREATE TABLE "IBColName" (
  "Group_ID" uuid,
  "No" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "SortNo" integer,
  "Col" varchar,
  "egNpCol" varchar,
  "Name" varchar,
  "Format" varchar,
  "Digit" integer,
  "ForEnergy" integer,
  "Visible" boolean,
  "PName1" varchar,
  "PName2" varchar,
  "PName3" varchar,
  "PTanni" varchar,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float,
  "PregCalc" integer,
  PRIMARY KEY ("Group_ID", "No")
);

CREATE TABLE "IncWeight" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "Val" float
);

CREATE TABLE "PregItem" (
  "Preg" int PRIMARY KEY,
  "Caption" varchar
);

CREATE TABLE "ProBase" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "C" float,
  "E" float,
  "F" float,
  "G" float
);

CREATE TABLE "StoreUpEnergy" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "DeEnergy" float,
  "UpEnergy" float
);

CREATE TABLE "Ene" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Pro" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ProEne" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Lip" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Sat" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Car" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Tot" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Ere" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ViD" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ToA" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ViK" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "VB1" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "VB2" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Nia" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "VB6" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "B12" (
  "older_min" int,
  "older_max" int,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Fol" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Pan" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Bio" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "ViC" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Nat" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Esa" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Kal" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Cal" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Mag" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Pho" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Iro" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Zin" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Cop" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Man" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Iod" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Sel" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Chr" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

CREATE TABLE "Mol" (
  "older_min" float,
  "older_max" float,
  "Sex" int,
  "mens" boolean,
  "preg" int,
  "EAR" float,
  "RDA" float,
  "AI" float,
  "UL" float,
  "DG" float,
  "GoalUL" float
);

COMMENT ON TABLE "GenerationsItem" IS '世代・年齢区分マスター';

COMMENT ON COLUMN "ActivityLevel"."older_min" IS '年齢別の活動レベル（下限）';

COMMENT ON COLUMN "ActLevel"."ActivityLevel" IS '身体活動区分';

COMMENT ON COLUMN "ActLevel"."ActivityVal" IS '身体活動レベル代表値';

COMMENT ON COLUMN "ActLevel"."Oldermin" IS '対象年齢下限';

COMMENT ON COLUMN "ActLevel"."Oldermax" IS '対象年齢上限';

COMMENT ON COLUMN "ActLevel"."AVmin" IS '身体活動レベル下限';

COMMENT ON COLUMN "ActLevel"."AVmax" IS '身体活動レベル上限';

COMMENT ON COLUMN "ActLevel"."Combo" IS 'コンボボックス用';

COMMENT ON COLUMN "ActLevel"."caption" IS '説明';

COMMENT ON COLUMN "BaseWeightC"."a" IS '推定平均必要量';

COMMENT ON COLUMN "BaseWeightC"."b" IS '推奨量';

COMMENT ON COLUMN "BMStandardVal"."older_min" IS '表6の数値';

COMMENT ON COLUMN "BMStandardVal"."BMBase" IS '基礎代謝基準値(kcal/体重kg/日)';

COMMENT ON COLUMN "BMStandardVal"."Val" IS '基礎代謝量(kcal)=基礎代謝基準値＊参照体重 1の位切り上げ';

COMMENT ON COLUMN "ColName"."No" IS 'オートナンバー型';

COMMENT ON COLUMN "IBColName"."No" IS 'オートナンバー型';

COMMENT ON COLUMN "IBColName"."SortNo" IS '並び順';

COMMENT ON COLUMN "IBColName"."Col" IS '列識別子';

COMMENT ON COLUMN "IBColName"."Name" IS '項目名称';

COMMENT ON COLUMN "IBColName"."Format" IS '表示書式';

COMMENT ON COLUMN "IBColName"."Digit" IS '桁数';

COMMENT ON COLUMN "IBColName"."Visible" IS '表示フラグ';

COMMENT ON COLUMN "IBColName"."PTanni" IS '単位';

COMMENT ON COLUMN "IBColName"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "IBColName"."RDA" IS '推奨量';

COMMENT ON COLUMN "IBColName"."AI" IS '目安量（0=目標, 1=目標未満, 2=目標以上, 3=目標以上 目標未満）';

COMMENT ON COLUMN "IBColName"."UL" IS '耐容上限量';

COMMENT ON COLUMN "IBColName"."DG" IS '目標量';

COMMENT ON COLUMN "IBColName"."PregCalc" IS '妊婦数値計算フラグ（0=加算, 1=交換）';

COMMENT ON COLUMN "IncWeight"."older_min" IS '表10';

COMMENT ON COLUMN "IncWeight"."Val" IS '体重増加量(kg/年)';

COMMENT ON COLUMN "ProBase"."C" IS '体たんぱく質(%)';

COMMENT ON COLUMN "ProBase"."E" IS '蓄積効率(%)';

COMMENT ON COLUMN "ProBase"."F" IS '維持必要量';

COMMENT ON COLUMN "ProBase"."G" IS '利用効率(%)';

COMMENT ON COLUMN "StoreUpEnergy"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "StoreUpEnergy"."DeEnergy" IS 'エネルギー密度(kcal／g)';

COMMENT ON COLUMN "StoreUpEnergy"."UpEnergy" IS 'エネルギー蓄積量(kcal／日)';

COMMENT ON COLUMN "Ene"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Ene"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Ene"."RDA" IS '推奨量';

COMMENT ON COLUMN "Ene"."AI" IS '目安量';

COMMENT ON COLUMN "Ene"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Ene"."DG" IS '目安量';

COMMENT ON COLUMN "Ene"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Pro"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Pro"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Pro"."RDA" IS '推奨量';

COMMENT ON COLUMN "Pro"."AI" IS '目安量';

COMMENT ON COLUMN "Pro"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Pro"."DG" IS '目安量';

COMMENT ON COLUMN "Pro"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ProEne"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ProEne"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ProEne"."RDA" IS '推奨量';

COMMENT ON COLUMN "ProEne"."AI" IS '目安量';

COMMENT ON COLUMN "ProEne"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ProEne"."DG" IS '目安量';

COMMENT ON COLUMN "ProEne"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Lip"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Lip"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Lip"."RDA" IS '推奨量';

COMMENT ON COLUMN "Lip"."AI" IS '目安量';

COMMENT ON COLUMN "Lip"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Lip"."DG" IS '目安量';

COMMENT ON COLUMN "Lip"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Sat"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Sat"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Sat"."RDA" IS '推奨量';

COMMENT ON COLUMN "Sat"."AI" IS '目安量';

COMMENT ON COLUMN "Sat"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Sat"."DG" IS '目安量';

COMMENT ON COLUMN "Sat"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Car"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Car"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Car"."RDA" IS '推奨量';

COMMENT ON COLUMN "Car"."AI" IS '目安量';

COMMENT ON COLUMN "Car"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Car"."DG" IS '目安量';

COMMENT ON COLUMN "Car"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Tot"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Tot"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Tot"."RDA" IS '推奨量';

COMMENT ON COLUMN "Tot"."AI" IS '目安量';

COMMENT ON COLUMN "Tot"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Tot"."DG" IS '目安量';

COMMENT ON COLUMN "Tot"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Ere"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Ere"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Ere"."RDA" IS '推奨量';

COMMENT ON COLUMN "Ere"."AI" IS '目安量';

COMMENT ON COLUMN "Ere"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Ere"."DG" IS '目安量';

COMMENT ON COLUMN "Ere"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ViD"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ViD"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ViD"."RDA" IS '推奨量';

COMMENT ON COLUMN "ViD"."AI" IS '目安量';

COMMENT ON COLUMN "ViD"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ViD"."DG" IS '目安量';

COMMENT ON COLUMN "ViD"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ToA"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ToA"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ToA"."RDA" IS '推奨量';

COMMENT ON COLUMN "ToA"."AI" IS '目安量';

COMMENT ON COLUMN "ToA"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ToA"."DG" IS '目安量';

COMMENT ON COLUMN "ToA"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ViK"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ViK"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ViK"."RDA" IS '推奨量';

COMMENT ON COLUMN "ViK"."AI" IS '目安量';

COMMENT ON COLUMN "ViK"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ViK"."DG" IS '目安量';

COMMENT ON COLUMN "ViK"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "VB1"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "VB1"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "VB1"."RDA" IS '推奨量';

COMMENT ON COLUMN "VB1"."AI" IS '目安量';

COMMENT ON COLUMN "VB1"."UL" IS '耐容上限量';

COMMENT ON COLUMN "VB1"."DG" IS '目安量';

COMMENT ON COLUMN "VB1"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "VB2"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "VB2"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "VB2"."RDA" IS '推奨量';

COMMENT ON COLUMN "VB2"."AI" IS '目安量';

COMMENT ON COLUMN "VB2"."UL" IS '耐容上限量';

COMMENT ON COLUMN "VB2"."DG" IS '目安量';

COMMENT ON COLUMN "VB2"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Nia"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Nia"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Nia"."RDA" IS '推奨量';

COMMENT ON COLUMN "Nia"."AI" IS '目安量';

COMMENT ON COLUMN "Nia"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Nia"."DG" IS '目安量';

COMMENT ON COLUMN "Nia"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "VB6"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "VB6"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "VB6"."RDA" IS '推奨量';

COMMENT ON COLUMN "VB6"."AI" IS '目安量';

COMMENT ON COLUMN "VB6"."UL" IS '耐容上限量';

COMMENT ON COLUMN "VB6"."DG" IS '目安量';

COMMENT ON COLUMN "VB6"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "B12"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "B12"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "B12"."RDA" IS '推奨量';

COMMENT ON COLUMN "B12"."AI" IS '目安量';

COMMENT ON COLUMN "B12"."UL" IS '耐容上限量';

COMMENT ON COLUMN "B12"."DG" IS '目安量';

COMMENT ON COLUMN "B12"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Fol"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Fol"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Fol"."RDA" IS '推奨量';

COMMENT ON COLUMN "Fol"."AI" IS '目安量';

COMMENT ON COLUMN "Fol"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Fol"."DG" IS '目安量';

COMMENT ON COLUMN "Fol"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Pan"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Pan"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Pan"."RDA" IS '推奨量';

COMMENT ON COLUMN "Pan"."AI" IS '目安量';

COMMENT ON COLUMN "Pan"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Pan"."DG" IS '目安量';

COMMENT ON COLUMN "Pan"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Bio"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Bio"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Bio"."RDA" IS '推奨量';

COMMENT ON COLUMN "Bio"."AI" IS '目安量';

COMMENT ON COLUMN "Bio"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Bio"."DG" IS '目安量';

COMMENT ON COLUMN "Bio"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "ViC"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "ViC"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "ViC"."RDA" IS '推奨量';

COMMENT ON COLUMN "ViC"."AI" IS '目安量';

COMMENT ON COLUMN "ViC"."UL" IS '耐容上限量';

COMMENT ON COLUMN "ViC"."DG" IS '目安量';

COMMENT ON COLUMN "ViC"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Nat"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Nat"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Nat"."RDA" IS '推奨量';

COMMENT ON COLUMN "Nat"."AI" IS '目安量';

COMMENT ON COLUMN "Nat"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Nat"."DG" IS '目安量';

COMMENT ON COLUMN "Nat"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Esa"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Esa"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Esa"."RDA" IS '推奨量';

COMMENT ON COLUMN "Esa"."AI" IS '目安量';

COMMENT ON COLUMN "Esa"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Esa"."DG" IS '目安量';

COMMENT ON COLUMN "Esa"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Kal"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Kal"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Kal"."RDA" IS '推奨量';

COMMENT ON COLUMN "Kal"."AI" IS '目安量';

COMMENT ON COLUMN "Kal"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Kal"."DG" IS '目安量';

COMMENT ON COLUMN "Kal"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Cal"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Cal"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Cal"."RDA" IS '推奨量';

COMMENT ON COLUMN "Cal"."AI" IS '目安量';

COMMENT ON COLUMN "Cal"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Cal"."DG" IS '目安量';

COMMENT ON COLUMN "Cal"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Mag"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Mag"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Mag"."RDA" IS '推奨量';

COMMENT ON COLUMN "Mag"."AI" IS '目安量';

COMMENT ON COLUMN "Mag"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Mag"."DG" IS '目安量';

COMMENT ON COLUMN "Mag"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Pho"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Pho"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Pho"."RDA" IS '推奨量';

COMMENT ON COLUMN "Pho"."AI" IS '目安量';

COMMENT ON COLUMN "Pho"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Pho"."DG" IS '目安量';

COMMENT ON COLUMN "Pho"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Iro"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Iro"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Iro"."RDA" IS '推奨量';

COMMENT ON COLUMN "Iro"."AI" IS '目安量';

COMMENT ON COLUMN "Iro"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Iro"."DG" IS '目安量';

COMMENT ON COLUMN "Iro"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Zin"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Zin"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Zin"."RDA" IS '推奨量';

COMMENT ON COLUMN "Zin"."AI" IS '目安量';

COMMENT ON COLUMN "Zin"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Zin"."DG" IS '目安量';

COMMENT ON COLUMN "Zin"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Cop"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Cop"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Cop"."RDA" IS '推奨量';

COMMENT ON COLUMN "Cop"."AI" IS '目安量';

COMMENT ON COLUMN "Cop"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Cop"."DG" IS '目安量';

COMMENT ON COLUMN "Cop"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Man"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Man"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Man"."RDA" IS '推奨量';

COMMENT ON COLUMN "Man"."AI" IS '目安量';

COMMENT ON COLUMN "Man"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Man"."DG" IS '目安量';

COMMENT ON COLUMN "Man"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Iod"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Iod"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Iod"."RDA" IS '推奨量';

COMMENT ON COLUMN "Iod"."AI" IS '目安量';

COMMENT ON COLUMN "Iod"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Iod"."DG" IS '目安量';

COMMENT ON COLUMN "Iod"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Sel"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Sel"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Sel"."RDA" IS '推奨量';

COMMENT ON COLUMN "Sel"."AI" IS '目安量';

COMMENT ON COLUMN "Sel"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Sel"."DG" IS '目安量';

COMMENT ON COLUMN "Sel"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Chr"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Chr"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Chr"."RDA" IS '推奨量';

COMMENT ON COLUMN "Chr"."AI" IS '目安量';

COMMENT ON COLUMN "Chr"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Chr"."DG" IS '目安量';

COMMENT ON COLUMN "Chr"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';

COMMENT ON COLUMN "Mol"."mens" IS 'Yes/No型';

COMMENT ON COLUMN "Mol"."EAR" IS '推定平均必要量';

COMMENT ON COLUMN "Mol"."RDA" IS '推奨量';

COMMENT ON COLUMN "Mol"."AI" IS '目安量';

COMMENT ON COLUMN "Mol"."UL" IS '耐容上限量';

COMMENT ON COLUMN "Mol"."DG" IS '目安量';

COMMENT ON COLUMN "Mol"."GoalUL" IS '上限(NLオリジナル) 目標量に下限、上限がある場合使用する';
